<?php

namespace Neoan\Enums;

enum GenericEvent
{
    case DATABASE_ADAPTER_CONNECTED;
    case BEFORE_DATABASE_TRANSACTION;
    case AFTER_DATABASE_TRANSACTION;
    case BEFORE_RENDERING;
    case REQUEST_HANDLER_INITIALIZED;
    case REQUEST_HEADERS_SET;
    case REQUEST_INPUT_PARSED;
    case ROUTE_HANDLER_INITIALIZED;
    case ROUTE_REGISTERED;
    case RESPONSE_HANDLER_SET;
    case BEFORE_RESPONSE;
    case ROUTE_INJECTION;
    case BEFORE_ROUTABLE_EXECUTION;
    case UNRECOVERABLE_ERROR;
}