name: Build

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  test:
    needs: [build]
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test
  coverage:
    needs: [ test ]
    name: coverage
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Comment code coverage
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./Tests/clover.xml
      - name: Store coverage output
        run: |
          output=$(composer run-script current-coverage)
          echo "::set-output name=percent::$output"
        id: pure-coverage
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'Test coverage'
          status: ${{ steps.pure-coverage.outputs.percent }}
          color: 'blue,555,daf'
          path: '.github/badges/test-badge.svg'
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: '.github/badges/test-badge.svg'
          if-no-files-found: error


      - name: Commit badge
        env:
          BADGE: '.github/badges/test-badge.svg'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'badges'